# Just publish_gui_release.yml from the latest UnderAnalyzer
name: Publish Single File build of UnderAnalyzer GUI

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Building-GUI:
    strategy:
      fail-fast: false

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build UndertaleModTool --no-restore
    - name: Publish UnderAnalyzer GUI
      run: |
        dotnet publish UndertaleModTool -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true --output windows-latest
    - name: Copy external files
      run: |
        cp ./README.md ./windows-latest
        cp ./LICENSE.txt ./windows-latest
        cp -r ./UndertaleModLib/GameSpecificData/ ./windows-latest/GameSpecificData/
    - name: Create zip for stable release Windows GUI
      run: |
        7z a -tzip UnderAnalyzer_GUI-isSingleFile-${{ github.run_number }}.zip ./windows-latest/* -mx0
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: v${{ github.run_number }}
        body: |
          This is the release of the single file build for UnderAnalyzer GUI.
        draft: false
        prerelease: false
    - name: Upload Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./UnderAnalyzer_GUI-isSingleFile-${{ github.run_number }}.zip
        asset_name: UnderAnalyzer_GUI-isSingleFile-${{ github.run_number }}.zip
        asset_content_type: application/zip

