# Just publish_gui_release.yml from the latest UnderAnalyzer
name: Publish Single File build of UnderAnalyzer GUI

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Building-GUI:

    strategy:
      fail-fast: false

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build UndertaleModTool --no-restore
    - name: Publish UnderAnalyzer GUI
      run: |
        dotnet publish UndertaleModTool -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true --output windows-latest
    - name: Copy external files
      run: |
        cp ./README.md ./windows-latest
        cp ./LICENSE.txt ./windows-latest
        cp -r ./UndertaleModLib/GameSpecificData/ ./windows-latest/GameSpecificData/
    - name: Create zip for stable release Windows GUI
      run: |
        7z a -tzip UnderAnalyzer_GUI-isSingleFile.zip ./windows-latest/* -mx0 
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: UnderAnalyzer_GUI-isSingleFile
          path: UnderAnalyzer_GUI-isSingleFile.zip
